### ISSUE TITLE
How to view/report messages after initial view?

### ISSUE THREAD

**Issue by iggyvolz** [futuresight/futurebb#148]
Cross-posted from http://futuresight.org/forums/tech-help/futuresight-how-to-viewreport-messages-after-initial-view

I'm working on using the administrative warning system as a system to ban users from an external service (I'm not using the ban system because users should still be able to access their forum account). The system works great, and the appeal is exactly what I need. However, there doesn't seem to be a way to report/appeal messages through the Warnings and Appeals page on the user profile. I'm not sure if I'm missing something, or this was an oversight that was never corrected. I'm able to report/appeal messages through the header panel if someone else sends me a message, but if I have no messages I can only see the text.

**Comment by jacob-g** [comment]
What's left is to correct the language on the appeal page. Currently it has a message that's overly generic and doesn't specify the exact action being taken.

**Comment by Krett12** [comment]
But I still don't understand. How does leaving a warning ban someone? Those just don't add up...

**Comment by iggyvolz** [comment]
I'm not sure where it went but I got an email notification saying Krett12 replied here asking how it would ban them by giving a warning.

The way I'm doing it is that a special account gives a warning to the user beginning with GAME_BAN followed by a reason for a ban, or GAME_UNBAN followed by a reason for an unban.  When logging into the game itself, it looks for the most recent warning from the special account (if any) - if the warning begins with GAME_BAN the client may not log into the game (which is hooked into the futureBB database)

**Comment by jacob-g** [comment]
I deleted the comment because it was off-topic (it doesn't relate to the actual changes that need to be made to FutureBB). Anyway, since it came up, the original comment was this:
"But I still don't understand. How does leaving a warning ban someone? Those just don't add up..."

**Comment by Krett12** [comment]
Well, it was related to what was being talked about. Please don't delete this one too.
