### ISSUE TITLE
Capitalized BBcode

### ISSUE THREAD

**Issue by iggyvolz** [futuresight/futurebb#164]
Just forwarding this on from a user of mine:
> I found that, if you [I]capitalise[/I] your BBCode, it doesn't work.

Is this intended or no?  If you wanted capitalized BBCode to work you could just use a strtolower() for detection.

**Comment by jacob-g** [comment]
It is intended that BBCode needs to be lowercase. This was designed in order to make parsing simpler and avoid confusion between stuff like l and I.
