### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by axisdos** [futuresight/futurebb#80]
Hey guys, I just found out about this project on Github right now. It looks really nice and seems like an SEO friendly forum software. I love the simple interface too. 

Is it still being developed actively? Thanks

**Comment by axisdos** [comment]
By the way, I downloaded v1.1 from the official site and when I go to install.php I'm getting this error. http://tangroup.co/install.php

Then I tried the latest version from Github (which I believe 1.3) the process of installing is fine until after I setup admin account. Then continue and it showed something like line 1044 (not sure if this is the correct line) about the admin account.

**Comment by jacob-g** [comment]
You're probably going to want to install version 1.2 from GitHub (https://github.com/futuresight/futurebb/releases/tag/v1.2), Version 1.3 does not have the installer updated to match the appropriate database structure yet, but v1.2 should work.
Please let me know how that goes.

Also, yes, this project is still active. I've just been really busy lately.
